### ISSUE TITLE
Add interactivity to map/results page

### ISSUE THREAD

**Issue by flibbertigibbet** [azavea/echo-locator#27]
Clicking a map marker for a neighborhood should change the selected neighborhood (show green arrow in sidebar card), and show the route to it on the map.

Clicking a card in the sidebar should go to the detail page (or have a stub method log to console, if detail page not yet implemented).

![image](https://user-images.githubusercontent.com/960264/52227151-c0f75080-287c-11e9-8135-1fec3f765234.png)

Depends on #25.

**Comment by lederer** [comment]
Let’s first try hover instead:

- hovering on a map marker OR sidebar card should highlight that neighborhood (change its map and sidebar marker to green; render its route)
- clicking a map marker OR sidebar card should go to that neighborhood’s detail page

If it turns out this feels too dynamic, we can try other interaction models.
