### ISSUE TITLE
Increase flexibility of grammar in translations

### ISSUE THREAD

**Issue by ktohalloran** [azavea/echo-locator#389]
Both the Spanish and Chinese translations pose unique challenges in terms of grammar and the way we have structured our translations within components. This issue is about restructuring the places where this grammar is currently incorrect or where our method does not work with the translations we need to add. This issue does not include all dynamic text; a list of affected phrases is available below. One way we got around this in other parts of the app for phrases that are not in this list was to use interpolation, replacing the entire phrase at once and simply handing the translation the dynamic values, such as was used to populate the tooltips. Another possibility is to introduce some form of logic to check for language and then piece together the sentence from there.

**Chinese**
The way some of the phrases are currently built and translated works for both English and Spanish but needs to be restructured to allow for reordering as required by Chinese grammar. For example, the phrase "Take [bus number] in [number] minutes" in the dock is currently structured with "Take", "in", and "minutes" as separate phrases that get translated separately and pieced together into a sentence along with the dynamic values within the component. This order of words does not work in that order in Chinese.

This is the list of impacted phrases; all are from the dock in the neighborhood detail view. Note that for the last two, clarification on the translation may be necessary.
* About [number of min] min via subway/bus from [destination] | 從[destination]方向乘地鐵/巴士約[number of min]分鐘
* Take [route number] in [number of min] minutes | 在[number of min]分鐘內乘坐 (it's unclear where in this translation the [route number] should go)
* Search for [number of br]br with max rent $[dollar amount] | 以最高租金搜索[number of br]臥房單位 (it's unclear where in this translation the [dollar amount] should go)

**Spanish**
The existing Spanish phrases aren't always grammatically correct and require special rules when reusing the same word across multiple parts of the app. For example, the app references the Spanish word "trabajo" in the Profile page destination dropdown menu and in the phrase "[mode of transportation] de trabajo" in the dock. While the word "trabajo" without an article makes sense for the dropdown menu, that word should become "el trabajo" when used in a sentence and, if the word before it is "de", should become "del trabajo."

This is the list of impacted phrases:
* [mode of transportation] from [destination] (dock, viewing recommendations)
* About [number of min] min via subway/bus from [destination] (dock, neighborhood detail view)

You should branch off of `release/2022-03-02` for this work and make the PR back to that same branch.

**Comment by ddohler** [comment]
Thanks for identifying these issues! As a general matter, I think the usual approach to addressing these types of issues where we've encoded assumptions about English grammar into the code is to refactor into longer strings and rely on `i18next`'s capabilities to generate the appropriate translated representation.

An easy case of this is pluralization and word ordering. For example, in cases where we have something like `{t('Units.About')} {roundedTripTime} {t('Units.Mins')}`, we should refactor to something like `{t('TripLengthDescription', {count: roundedTripTime})}` , which would correspond to locale files that look like
```
TripLengthDescription_one: "About {{count}} minute",
TripLengthDescription_other: "About {{count}} minutes",
```
And then we can adjust the word / character ordering and add fewer or more numeric cases for other languages as necessary, relying on [i18next's plurality functionality](https://www.i18next.com/translation-function/plurals).

The `del trabajo` case is trickier. Looking through the i18next documentation, the feature that looks to me like it is intended for addressing these types of problems is the use of [contexts](https://www.i18next.com/translation-function/context) . The context allows the selection of a different translation depending on which flag is passed in. For the `trabajo` example you gave, this might look something like this (I didn't look closely at how this is currently done so this is more of a rough sketch than an actual solution): `t('ModeFromDestination', {mode: selectedMode, context: "article1"})`. This would result in a locale file that looks like this:
```
{
  ModeFromDestination_article1: "{{mode}} de la {{destination}}"
  ModeFromDestination_article2: "{{mode}} del {{destination}}"
  ModeFromDestination: "{{mode}} de {{destination}}" // If needed, but in English we'd have only this.
}
```

The part I'm not sure sure about here is where to store the information about which article goes with which noun. It looks like it's possible to return objects as translation keys, so my initial pass would be to do something like this in the locale file (again, just a sketch)
```
  Work: {value: "trabajo", articleContext: "article2"}
```
And then pull out the value for `articleContext` when inserting into a context that may require an article. That seems like it would add some extra work wherever the `Work` key needs to get used to handle the availability (or not, depending on language) of the article key, and perhaps there would need to be other context keys added for Chinese (there certainly would in say, Russian), but it generally seems like it would limit the process for handling new and interesting grammatical requirements to "Add a context key differentiating the thing we need to encode and pass it to i18next", which seems relatively straightforward and easy to repeat.

The other option I've seen for this kind of thing is just to avoid sentences entirely. So rather than "Rail from work", switch to
```
Trip info:
Mode: Rail
Starting location: Work
```

Another thing I noticed is that it may also be helpful to utilize the [Trans component](https://react.i18next.com/latest/trans-component) to make handling the React structure easier.

Does this sound like it's a path forward for all the items you noted?

**Comment by ktohalloran** [comment]
Hi Derek, thanks for thinking through these things and suggesting a path forward. As described above, it does sound like `react-i18next` does have a way of working with all of the situations, which is good to hear. I agree that these all sound like paths forward, with pros and cons to both. While there are places where a bulleted list would look a bit odd, adding in logic to use proper contexts sounds complex and like it could injure readability. Perhaps this issue should include a discussion with @lederer on where bulleted lists can feasibly be used to replace full sentences, followed by exploring the application of `react-i18next`'s capacity for plurals and contexts to remaining strings.

**Comment by ddohler** [comment]
We discussed this with BHA and they're going to get us revised language for these areas so that we avoid sentence structure.

**Comment by ddohler** [comment]
Update: We have some new translations now, but they may not cover everything in this issue, so we're going to just have to make do with what we have to keep this from dragging on too much. So this task is now to:

Use your best judgment to rework the sentence-based structures identified in this issue into key: value format so that they can be more easily translated, and update the translation files appropriately.
