### ISSUE TITLE
Translate text in dock dropdown menus

### ISSUE THREAD

**Issue by ktohalloran** [azavea/echo-locator#391]
The wiring for translating and majority of translation strings have been added (PRs [377](https://github.com/azavea/echo-locator/pull/377) and [390](https://github.com/azavea/echo-locator/pull/390)); however, the "from destination" and Peak/Off Peak/Peak No Express/Off Peak No Express dropdown menus in the neighborhood detail view dock have not been translated. For the "from destination" menu, there seems to be an issue with how state understands state values set in one language and then displayed in another, as the language of the destination tag always matches the language in which the destination was added, rather than the language controlled by the toggle. For the Peak/Off Peak menu, there seems to be a disconnect between how the option labels need to look to work with `i18next` and the option labels that state expects. Overall, it may be worth exploring how `i18next` and state work (or don't) together in the [React-i18next documentation](https://react.i18next.com/).

Following identification of and a solution for the disconnect, relevant translation strings also need to be added to each language's relevant translation file for the Peak/ Off Peak menu (all destinations already have translations). As a note, as of the creation of this issue, we only had translations for "Peak" (什麼時候高峰期) and "Off Peak" (非高峰) in Chinese. Additional translations are needed for all 4 options in Spanish and for the "No Express" options in Chinese.

**Comment by ddohler** [comment]
I haven't confirmed this, but from what you describe, it sounds like we're probably using the same string for both state tracking and display to users, which causes problems when we try to translate because the state variable doesn't get translated. So I think the solution should be to split apart the state tracking from user display: we should make sure that we have a non-user-visible token, that doesn't depend on language, which is used internally to track this type of state, and then we use that to determine which string to display to the user depending on their chosen language. Does that sound right?

**Comment by ktohalloran** [comment]
Hi Derek, thanks for sharing your thoughts on this issue. Yes, that does sound right. I also don't exactly know without attempting to apply this theory, but my guess would be that we could simply re-use the non-user-visible token that `i18next` is already using to reference the string across the various translation files. I think if we can give state that token instead, the places where that value is then used may translate the same way as all the other strings do.
