### ISSUE TITLE
Restrict Cognito domains

### ISSUE THREAD

**Issue by flibbertigibbet** [azavea/echo-locator#52]
Add domain restrictions to the Cognito configuration for staging, production, and local development.

**Comment by jeancochrane** [comment]
I couldn't figure out how to do this in 15 minutes, so per our conversation in standup today I'm going to put it back in the queue.

My initial assumption was that we could add this restriction through the `App client settings` portion of the dashboard, by defining callback/sign-in/sign-out URLs for each app client. This didn't work, unfortunately, which I think is because this portion of the settings only applies to the hosted UI. There must be some other setting that pertains to our login flow (which uses a custom login page on the client side) but I couldn't immediately find it in the console.

**Comment by flibbertigibbet** [comment]
From [this conversation](https://stackoverflow.com/a/52760998), it looks like the restriction would require a custom Lambda hook.

**Comment by hectcastro** [comment]
Closing because there isn't a straightforward Cognito configuration setting to whitelist domains.
