### ISSUE TITLE
Fix add Destination locations in admin

### ISSUE THREAD

**Issue by rachelekm** [azavea/echo-locator#540]
When adding a new destination from the admin, the location point does not update. The point remains the default in the location field on User Profile as well as when displaying the origin point on the frontend map. However, if adding a new destination from the frontend, the location point does correctly update for both the location field in admin and as a point on the map on the frontend. The location points for user destination's migrated from S3 were correctly set, so this seems exclusive to adding a new destination from the admin. See screenshots below
If added Destination through admin:
<img width="1347" alt="Screen Shot 2022-05-31 at 2 10 36 PM" src="https://user-images.githubusercontent.com/36374797/171256482-05aa8fc9-c3ab-46dc-87a9-7dc332d42c5a.png">
<img width="547" alt="Screen Shot 2022-05-31 at 1 26 33 PM" src="https://user-images.githubusercontent.com/36374797/171256524-a8ddb165-c1dd-4412-9318-087154918f2c.png">

If added Destination through frontend edit-profile:
<img width="1349" alt="Screen Shot 2022-05-31 at 2 14 07 PM" src="https://user-images.githubusercontent.com/36374797/171256649-dbc2e388-7164-40cd-927d-a9dabac19661.png">
<img width="919" alt="Screen Shot 2022-05-31 at 2 11 03 PM" src="https://user-images.githubusercontent.com/36374797/171256425-f1bc71fb-47d2-45a6-8c9f-5675ffa43f6b.png">

**Comment by ddohler** [comment]
Thanks for adding this! The reason this is happening is that in order to go from an address to a coordinate pair it's necessary to geocode the address. On the frontend, we use Mapbox's geocoding service to do this, but on the backend we haven't added any geocoding, so the fields are essentially independent. I think the best thing to do for now is to treat these fields as read-only in the admin so that they can only change via the frontend, which will ensure that the addresses get geocoded correctly. I mentioned this to BHA during our demo last week and they were okay with it. If we run into problems with people trying to change them then we could enforce their read-only status in the admin setup.

**Comment by rachelekm** [comment]
Thank you for clarifying, that makes sense! I'll go ahead and close this issue.
