### ISSUE TITLE
Update neighborhood data

### ISSUE THREAD

**Issue by ddohler** [azavea/echo-locator#563]

**Comment by aaronxsu** [comment]
I downloaded the neighborhood CSV data from the channel. Here are some findings:
1. The fields from the column header row and the order match those of the exiting `neighborhoods.cvs`. This means that we should be able to run the existing scripts to create those JSON files.
2. With some minor edits of the `./neighborhood_data/update_data.sh` (commented out some irrelevant steps), the `neighborhoods.json`, `neighborhood_bounds.json`, and the corresponding images were generated fine without terminal errors
3. The current management script that imports neighborhood data pulls the above mentioned JSON from S3 and inserts them to the database. It also uses the S3 location of the bucket/prefix where the images are stored and inserts the image S3 URL of each image along with the neighborhood JSON data to the DB.

Communicated above with @ddohler and here is a summary of a plan to proceed:
1. Upload the `neighborhoods.json`, `neighborhood_bounds.json` to the S3 `*-data-*` bucket so that the management script will pull the updated neighborhoods info before insert/update to DB.
2. Upload the images to the `*-staging-site-*` bucket to refresh the images
3. Run the management script locally in the dev DB and check the updates neighborhoods
4. If look fine, run it on staging
